name: deploy

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/psb_ui_chart.yml'
      - 'chart/**'
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Build app
      uses: hyoo-ru/mam_build@master2
      with:
        token: ${{ secrets.GH_PAT }}
        package: 'psb/ui'
        modules: 'chart'
